# Generated by Django 5.0.1 on 2026-03-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='bonus_points',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attempt',
            name='is_weekly_milestone',
            field=models.BooleanField(default=False),
        ),
    ]
