# Generated by Django 5.0.1 on 2026-03-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='leaderboard_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='new_features',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='quiz_reminders',
            field=models.BooleanField(default=True),
        ),
    ]
