# Generated by Django 5.0.1 on 2026-03-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_leaderboard_updates_user_new_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_quiz_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
